INSERT INTO roles VALUES (1, 'ROLE_ADMIN');
INSERT INTO roles VALUES (2, 'ROLE_MANAGER');
INSERT INTO roles VALUES (3, 'ROLE_ASSOCIATE');
INSERT INTO roles VALUES (4, 'ROLE_TESTER');
INSERT INTO roles VALUES (5, 'ROLE_DEVELOPER');
